В коде мы удаляем throws Exception из сигнатуры метода getKey(), так как теперь метод будет обрабатывать
исключения внутри себя.
Мы добавляем цикл while в метод getKey(), чтобы предоставить пользователю еще одну попытку ввода
значения ключа в случае возникновения исключения.
В блоке try метода getKey(), мы просим пользователя ввести ключ с помощью Scanner.
Если взаимодействие с Scanner вызывает исключение, мы перехватываем его в блоке catch и выводим сообщение
об ошибке. Если ввод успешен, мы вызываем метод printKey() для печати значения ключа.
В методе printKey() мы просто выводим значение ключа.
Теперь программа будет продолжать работу после возникновения исключения, предоставляя пользователю
возможность повторить ввод.